---
- name: Install nginx
  apt:
   name:
    - nginx
   state: present

- name: Copy Nginx server configuration in place
  template:
          src: templates/https.test.conf.j2
          dest: /etc/nginx/sites-enabled/https.test.conf
          mode: 0644

- name: Reload Nginx
  shell: systemctl reload nginx  
